name: Kernel test

on:
  workflow_dispatch:
  
jobs:
  kernel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: pip install telethon

      - name: Restore session
        run: |
          echo "${{ secrets.TG_SESSION }}" | base64 -d > tg.session

      - name: Download kernel
        env:
          API_ID: ${{ secrets.TG_API_ID }}
          API_HASH: ${{ secrets.TG_API_HASH }}
          CHAT_ID: ${{ secrets.TG_CHAT_IDFLIPPY }}
        run: |
          python << 'PY'
          import re, os
          from telethon import TelegramClient

          api_id = int(os.environ["API_ID"])
          api_hash = os.environ["API_HASH"]
          chat_id = int(os.environ["CHAT_ID"])

          client = TelegramClient("tg", api_id, api_hash)

          async def main():
              await client.start()

              files = {}
              ver_latest = None

              async for msg in client.iter_messages(chat_id, limit=200):
                  if not msg.file:
                      continue

                  name = msg.file.name or ""
                  m = re.search(r'(\d+\.\d+\.\d+-flippy-\d+\+)', name)
                  if not m:
                      continue

                  ver = m.group(1)

                  if ver_latest is None or ver > ver_latest:
                      ver_latest = ver
                      files = {}

                  if ver == ver_latest:
                      if name.startswith(("header-6.18", "modules-6.18", "boot-6.18", "dtb-amlogic-6.18")):
                          files[name] = msg

              if len(files) != 4:
                  print("Kernel incomplete")
                  return

              base_dir = f"dl/{ver_latest}"
              os.makedirs(base_dir, exist_ok=True)

              for name, msg in files.items():
                  path = f"{base_dir}/{name}"
                  print("Downloading", name, "->", path)
                  await msg.download_media(path)

              tar_name = f"{ver_latest}.tar.gz"
              os.system(f"tar -czf {tar_name} -C dl {ver_latest}")

          with client:
              client.loop.run_until_complete(main())
          PY

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: kernel_stable
          name: Kernel_Stable
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
